parameters:
    GuildCharacterService.class: LaDanse\ServicesBundle\Service\GuildCharacterService
    GameDataService.class: LaDanse\ServicesBundle\Service\GameDataService
    SettingsService.class: LaDanse\ServicesBundle\Service\SettingsService
    AccountService.class: LaDanse\ServicesBundle\Service\AccountService

services:
    LaDanse.GuildCharacterService:
        class: "%GuildCharacterService.class%"
        arguments: ['@service_container']
    LaDanse.GameDataService:
        class: "%GameDataService.class%"
        arguments: ['@service_container']
    LaDanse.SettingsService:
        class: "%SettingsService.class%"
        arguments: ['@service_container']
    LaDanse.AccountService:
        class: "%AccountService.class%"
        arguments: ['@service_container']