INSERT INTO LaDanseDB.GameClass(id, name) VALUES (1, "Warrior");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (2, "Paladin");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (3, "Hunter");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (4, "Rogue");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (5, "Priest");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (6, "Death Knight");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (7, "Shaman");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (8, "Mage");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (9, "Warlock");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (10, "Monk");
INSERT INTO LaDanseDB.GameClass(id, name) VALUES (11, "Druid");