INSERT INTO LaDanseDB.GameRace(id, name) VALUES (6, "Tauren");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (5, "Undead");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (2, "Orc");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (7, "Gnome");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (9, "Goblin");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (1, "Human");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (8, "Troll");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (24, "Pandaren");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (11, "Draenei");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (22, "Worgen");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (10, "Blood Elf");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (4, "Night Elf");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (3, "Dward");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (25, "Pandaran (Horde)");
INSERT INTO LaDanseDB.GameRace(id, name) VALUES (26, "Pandaren (Alliance)");