parameters:
    CommentService.class: LaDanse\CommentBundle\Service\CommentService

services:
    LaDanse.CommentService:
        class: "%CommentService.class%"
        arguments: ['@service_container']