language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
    - mysql

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - mysqladmin create LaDanseDB -u root
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - bin/console doctrine:database:create --env=test --no-interaction --if-not-exists
    - bin/console doctrine:migrations:migrate --env=test --allow-no-migration --no-interaction
    - bin/console sp:bower:install --env=test --no-debug
    - bin/console cache:warmup --env=test

script:
    - ./bin/phpspec run -fpretty --verbose
    - ./bin/behat  --no-snippets --no-paths --verbose

matrix:
    allow_failures:
          - php: hhvm