imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

security:
    firewalls:
        main:
            http_basic: ~

liip_functional_test: ~

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        #driver:   "%test_database_driver%"
        #host:     "%test_database_host%"
        #port:     "%test_database_port%"
        #dbname:   "%test_database_name%"
        #user:     "%test_database_user%"
        #password: "%test_database_password%"
        driver:   pdo_sqlite
        path:     %kernel.cache_dir%/test.db
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
