imports:
    - { resource: parameters.yml }
    - { resource: version.yml }
    - { resource: security.yml }
    - { resource: hwi_oauth.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets:
        version: "%deployment_version%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        auth: "@LaDanse.AuthenticationService"
        deployment_name: "%deployment_name%"
        deployment_type: "%deployment_type%"
        deployment_version: "%deployment_version%"

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [LaDanseRestBundle, LaDanseDomainBundle, LaDanseServicesBundle, LaDanseSiteBundle]
        directories: ["%kernel.root_dir%/../src"]

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - LaDanseSiteBundle
        - LaDanseBootstrapBundle
        - LaDanseAngularBundle
        - CoderSpottingToastMessageBundle
        - FOSUserBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: "%nodejs_binary_path%"
            node_paths: "%nodejs_module_path%"
            apply_to: ".less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

mopa_bootstrap:
    form:
        show_legend: false # default is true
        show_child_legend: false # default is true
        error_type: block # or inline which is default

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: LaDanse\DomainBundle\Entity\Account
    from_email:
            address:        noreply@ladanse.org
            sender_name:    La Danse Website
    registration:
            confirmation:
                enabled:    false # change to true for required email confirmation
                template:   FOSUserBundle:Registration:email.txt.twig

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }

trt_swift_css_inliner:
    inliner_class: TijsVerkoyen\CssToInlineStyles\CssToInlineStyles
    cleanup: false
    strip_original_style_tags: false
    exclude_media_queries: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: LaDanseDomain\Migrations
    table_name: migration_versions
    name: La Danse Website Migrations

services:
  LaDanse.PasswordResetting:
      class: LaDanse\SiteBundle\EventListener\PasswordResettingListener
      arguments: [ "@router" ]
      tags:
          - { name: kernel.event_subscriber }
  fos_user.doctrine_registry:
      alias: doctrine
  cache:
      class: Doctrine\Common\Cache\FilesystemCache
      arguments: [ "%kernel.cache_dir%" ]

sp_bower:
  bin: "%bower_binary_path%"
  assetic:
    nest_dependencies: false
  bundles:
    LaDanseSiteBundle: ~
    LaDanseAngularBundle: ~

nelmio_api_doc: ~