imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["ladanse"]
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      grouped
        grouped:
            type:    group
            members: [streamed, ladanse, buffered]
        streamed:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        buffered:
            type:    buffer
            handler: swift
        swift:
            type:       swift_mailer
            from_email: "noreply@ladanse.org"
            to_email:   "%admin_email%"
            subject:    "An Error Occurred on La Danse website!"
            level:      debug
        ladanse:
            type:     stream
            path:     "%kernel.logs_dir%/ladanse.log"
            level:    debug
            channels: [ladanse]
