la_danse_common:
    resource: "@LaDanseCommonBundle/Resources/config/routing.yml"
    prefix:   /

la_danse_domain:
    resource: "@LaDanseDomainBundle/Controller/"
    type:     annotation
    prefix:   /

la_danse_site:
    resource: "@LaDanseSiteBundle/Resources/config/routing.yml"
    prefix:	  /
    