security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                always_use_default_target_path: false
                default_target_path:            /menu
            logout:       true
            anonymous:    true
            remember_me:
                        key:      "%secret%"
                        lifetime: 31536000 # 365 days in seconds
                        path:     /
                        domain:   ~ # Defaults to the current domain from $_SERVER
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/calendar, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/events, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/settings, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/claims, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/teamspeak, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/gallery, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/forum, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/help, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/menu, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/feedback, role: IS_AUTHENTICATED_REMEMBERED }

