parameters:
#    la_danse_common.example.class: LaDanse\CommonBundle\Example

services:
#    la_danse_common.example:
#        class: %la_danse_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
