EventRouting:
    resource: "@LaDanseRestBundle/Controller/Events"
    type:     annotation
    prefix:   /api/events

ForumRouting:
    resource: "@LaDanseRestBundle/Controller/Forum"
    type:     annotation
    prefix:   /services/forum

CommentRestRouting:
    resource: "@LaDanseRestBundle/Controller/Comments"
    type:     annotation
    prefix:   /services/comment

GameDataRestRouting:
    resource: "@LaDanseRestBundle/Controller/GameData"
    type:     annotation
    prefix:   /services/gamedata

CharacterRestRouting:
    resource: "@LaDanseRestBundle/Controller/Character"
    type:     annotation
    prefix:   /services
