EventRouting:
    resource: "@LaDanseRestBundle/Controller/Events"
    type:     annotation
    prefix:   /api/events

ForumRouting:
    resource: "@LaDanseRestBundle/Controller/Forum"
    type:     annotation
    prefix:   /services/forum

CommentRestRouting:
    resource: "@LaDanseRestBundle/Controller/Comments"
    type:     annotation
    prefix:   /services/comment

GameDataRestRouting:
    resource: "@LaDanseRestBundle/Controller/GameData"
    type:     annotation
    prefix:   /api/gamedata

GuildRestRouting:
    resource: "@LaDanseRestBundle/Controller/Guild"
    type:     annotation
    prefix:   /api/guilds

CharacterRestRouting:
    resource: "@LaDanseRestBundle/Controller/Character"
    type:     annotation
    prefix:   /api/characters

DiscordGrantRouting:
    resource: "@LaDanseRestBundle/Controller/DiscordAuth"
    type:     annotation
    prefix:   /api/discord

ProfileRouting:
    resource: "@LaDanseRestBundle/Controller/Profile"
    type:     annotation
    prefix:   /api/profile

QueriesRestRouting:
    resource: "@LaDanseRestBundle/Controller/Queries"
    type:     annotation
    prefix:   /api/queries

CallbackRouting:
    resource: "@LaDanseRestBundle/Controller/Callback"
    type:     annotation
    prefix:   /api/callback

