WelcomeRouting:
    resource: "@LaDanseSiteBundle/Controller/Welcome"
    type:     annotation
    prefix:   /

CalendarRouting:
    resource: "@LaDanseSiteBundle/Controller/Calendar"
    type:     annotation
    prefix:   /calendar

EventsRouting:
    resource: "@LaDanseSiteBundle/Controller/Events"
    type:     annotation
    prefix:   /events

SettingsRouting:
    resource: "@LaDanseSiteBundle/Controller/Settings"
    type:     annotation
    prefix:   /settings

ClaimsRouting:
    resource: "@LaDanseSiteBundle/Controller/Claims"
    type:     annotation
    prefix:   /claims

TeamSpeakRouting:
    resource: "@LaDanseSiteBundle/Controller/TeamSpeak"
    type:     annotation
    prefix:   /teamspeak

GalleryRouting:
    resource: "@LaDanseSiteBundle/Controller/Gallery"
    type:     annotation
    prefix:   /gallery

ForumRouting:
    resource: "@LaDanseSiteBundle/Controller/Forum"
    type:     annotation
    prefix:   /forum

RegistrationRouting:
    resource: "@LaDanseSiteBundle/Controller/Registration"
    type:     annotation
    prefix:   /registration

MenuRouting:
    resource: "@LaDanseSiteBundle/Controller/Menu"
    type:     annotation
    prefix:   /menu

PrivacyPolicyRouting:
    resource: "@LaDanseSiteBundle/Controller/Privacy"
    type:     annotation
    prefix:   /privacy

AboutRouting:
    resource: "@LaDanseSiteBundle/Controller/About"
    type:     annotation
    prefix:   /about

FeedbackRouting:
    resource: "@LaDanseSiteBundle/Controller/Feedback"
    type:     annotation
    prefix:   /feedback

RosterRouting:
    resource: "@LaDanseSiteBundle/Controller/Roster"
    type:     annotation
    prefix:   /roster

RedirectRouting:
    resource: "@LaDanseSiteBundle/Controller/Redirect"
    type:     annotation
    prefix:   /redirect

ActivityStreamRouting:
    resource: "@LaDanseSiteBundle/Controller/ActivityStream"
    type:     annotation
    prefix:   /activitystream

CharactersRouting:
    resource: "@LaDanseSiteBundle/Controller/Characters"
    type:     annotation
    prefix:   /characters

GuildMeet:
    path: /guildmeet
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    LaDanseSiteBundle:static:guildmeet.html.twig