LaDanseSiteRouting:
    resource: "@LaDanseSiteBundle/Controller"
    type:     annotation
    prefix:   /

CalendarRouting:
    resource: "@LaDanseSiteBundle/Controller/Calendar"
    type:     annotation
    prefix:   /calendar

EventsRouting:
    resource: "@LaDanseSiteBundle/Controller/Events"
    type:     annotation
    prefix:   /events

SettingsRouting:
    resource: "@LaDanseSiteBundle/Controller/Settings"
    type:     annotation
    prefix:   /settings

ClaimsRouting:
    resource: "@LaDanseSiteBundle/Controller/Claims"
    type:     annotation
    prefix:   /claims

TeamSpeakRouting:
    resource: "@LaDanseSiteBundle/Controller/TeamSpeak"
    type:     annotation
    prefix:   /teamspeak

GalleryRouting:
    resource: "@LaDanseSiteBundle/Controller/Gallery"
    type:     annotation
    prefix:   /gallery

ForumRouting:
    resource: "@LaDanseSiteBundle/Controller/Forum"
    type:     annotation
    prefix:   /forum

HelpRouting:
    resource: "@LaDanseSiteBundle/Controller/Help"
    type:     annotation
    prefix:   /help

RegistrationRouting:
    resource: "@LaDanseSiteBundle/Controller/Registration"
    type:     annotation
    prefix:   /registration

MenuRouting:
    resource: "@LaDanseSiteBundle/Controller/Menu"
    type:     annotation
    prefix:   /menu

PrivacyPolicyRouting:
    resource: "@LaDanseSiteBundle/Controller/Privacy"
    type:     annotation
    prefix:   /privacy
    