services:
    LaDanse.TwigHeaderAndBack:
        class: "LaDanse\SiteBundle\Twig\TwigHeaderAndBackExtension"
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    LaDanse.TwigFeatureToggle:
        class: "LaDanse\SiteBundle\Twig\TwigFeatureToggleExtension"
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }